export const CHANGE_CITY = `CHANGE_CITY`;
export const CHANGE_ACTIVE_CARD = `CHANGE_ACTIVE_CARD`;
export const LOAD_OFFERS_START = `LOAD_OFFERS_START`;
export const LOAD_OFFERS_SUCCESS = `LOAD_OFFERS_SUCCESS`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
export const SEND_REVIEW_START = `SEND_REVIEW_START`;
export const SEND_REVIEW_SUCCESS = `SEND_REVIEW_SUCCESS`;

export const POST_FAVORITE_SUCCESS = `POST_FAVORITE_SUCCESS`;
export const POST_FAVORITE_START = `POST_FAVORITE_START`;
export const FETCH_START = `FETCH_START`;
export const FETCH_SUCCESS = `FETCH_SUCCESS`;
export const FETCH_ERROR = `FETCH_ERROR`;
