export const CHANGE_CITY = `CHANGE_CITY`;
export const CHANGE_ACTIVE_CARD = `CHANGE_ACTIVE_CARD`;
export const LOAD_OFFERS_START = `LOAD_OFFERS_START`;
export const LOAD_OFFERS_SUCCESS = `LOAD_OFFERS_SUCCESS`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
